---
name: WWW-HTMLTagAttributeCounter
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: access a webpage and count number of tags or attributes
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::TokeParser::Simple: 3.15
  LWP::UserAgent: 2.036
  overload: 1.04
build_requires:
  Test::More: 0
provides:
  WWW::HTMLTagAttributeCounter:
    file: lib/WWW/HTMLTagAttributeCounter.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
