---
abstract: 'access a webpage and count number of tags or attributes'
author:
  - "Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-HTMLTagAttributeCounter
provides:
  WWW::HTMLTagAttributeCounter:
    file: lib/WWW/HTMLTagAttributeCounter.pm
    version: 0.0103
requires:
  Class::Accessor::Grouped: 0
  HTML::TokeParser::Simple: 3.15
  LWP::UserAgent: 2.036
  overload: 1.04
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0103
